name: Gitleaks

on:

  push:
    branches: 
      - master
      - main
      - develop
      - development
      - qa
      
  pull_request:
    branches: 
      - master
      - main
      - develop
      - development
      - qa

jobs:
  key_leak-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          
      - name: Gitleaks
        run: |
          pip install detect-secrets
          detect-secrets scan ./ --all-files > secrets.html
          
      - name: ls
        run: |
          ls
          
      - name: Export Report
        if: "${{ always() }}"
        uses: actions/upload-artifact@v2
        with:
          name: key_leak-report
          path: ./secrets.html
